[workspace]
members = ["nrf52-firmware", "pc-software", "uart-protocol"]

[profile.dev]
incremental = false
codegen-units = 1
debug = true
lto = false

[profile.release]
codegen-units = 1
debug = true
lto = true
opt-level = 3
